/** Build-time loaders over site/src/data/ (generated by `aidag export-site`). */
import fs from 'node:fs';
import path from 'node:path';

// process.cwd() is the site/ project root both in `astro dev` and `astro build`
// (import.meta.url would point into dist/.prerender after bundling).
const DATA_DIR = path.join(process.cwd(), 'src', 'data');

export interface PartyInfo {
  name: string;
  color: string;
  bloc: string;
  seats_order: number;
}

export interface Meta {
  run_id: string | null;
  n_cases: number;
  parties: Record<string, PartyInfo>;
  hemicycle_order: string[];
  attribution: string;
}

export interface ActualPosition {
  position: string;
  n_ja: number;
  n_nej: number;
  n_avstar: number;
  n_franvarande: number;
  cohesion: number;
}

export interface AiDecision {
  rost: string;
  confidence: string;
  coverage: string;
  motivering: string;
  citations: { document: string; quote: string }[];
  flags: string[];
  model: string;
}

export interface CompactMeanings {
  ja_sv: string;
  nej_sv: string;
  avstar_sv: string;
  ja_en: string;
  nej_en: string;
  avstar_en: string;
}

export interface CaseData {
  compact?: CompactMeanings;
  votering_id: string;
  rm: string;
  beteckning: string;
  punkt: number;
  dok_id: string;
  datum: string;
  utskott: string;
  rubrik: string;
  dok_titel: string;
  forslag_text: string;
  notis: string;
  alternatives: { alt_id: string; text: string; source_partier: string[] }[];
  actual: Record<string, ActualPosition>;
  ai: Record<string, AiDecision>;
  probe: { recalls_case: boolean; exact_match_count: number } | null;
  seats: [string, string, string, string][]; // [parti, rost, namn, valkrets]
  references: { dok_id: string; typ: string; label: string; titel: string; undertitel: string }[];
  source_url: string;
  fulltext_url: string;
  votering_url: string;
  riksdagen_url: string;
}

export interface IndexRow {
  id: string;
  datum: string;
  rm: string;
  bet: string;
  punkt: number;
  utskott: string;
  rubrik: string;
  titel: string;
  agree: number;
  compared: number;
  hasAi: boolean;
}

function readJson<T>(rel: string): T {
  return JSON.parse(fs.readFileSync(path.join(DATA_DIR, rel), 'utf-8')) as T;
}

export const getMeta = (): Meta => readJson<Meta>('meta.json');
export const getIndex = (): IndexRow[] => readJson<IndexRow[]>('index/cases-index.json');
export const getCase = (id: string): CaseData => readJson<CaseData>(`cases/${id}.json`);

export function getAggregate<T>(name: string): T | null {
  const p = path.join(DATA_DIR, 'aggregates', `${name}.json`);
  return fs.existsSync(p) ? (JSON.parse(fs.readFileSync(p, 'utf-8')) as T) : null;
}

export function listCaseIds(): string[] {
  return fs
    .readdirSync(path.join(DATA_DIR, 'cases'))
    .filter((f) => f.endsWith('.json'))
    .map((f) => f.replace(/\.json$/, ''));
}

export function listCorpusDocs(): string[] {
  const dir = path.join(DATA_DIR, 'corpus');
  if (!fs.existsSync(dir)) return [];
  return fs
    .readdirSync(dir)
    .filter((f) => f.endsWith('.txt'))
    .map((f) => f.replace(/\.txt$/, ''));
}

export function getCorpusDoc(slug: string): string {
  return fs.readFileSync(path.join(DATA_DIR, 'corpus', `${slug}.txt`), 'utf-8');
}

/** Slug of the corpus document a citation points at, or null if not published. */
export function citationDocSlug(party: string, document: string): string | null {
  if (document === 'valmanifest') return `valmanifest-2022-${party.toLowerCase()}`;
  if (document === 'tidoavtalet') return 'tidoavtalet-2022';
  return null;
}

/** URL text-fragment for deep-linking a verbatim quote inside a document page. */
export function quoteFragment(quote: string): string {
  const words = quote.trim().split(/\s+/);
  if (words.length <= 8) return encodeURIComponent(words.join(' '));
  const start = words.slice(0, 5).join(' ');
  const end = words.slice(-4).join(' ');
  return `${encodeURIComponent(start)},${encodeURIComponent(end)}`;
}
