/** Build-time loaders over site/src/data/ (generated by `aidag export-site`). */
import fs from 'node:fs';
import path from 'node:path';
import { casingLexicon, stripInvisible, type CasingLexicon, type CorpusBlockFile } from './doctext';
import type { AnchorSummary } from './anchors';

// process.cwd() is the site/ project root both in `astro dev` and `astro build`
// (import.meta.url would point into dist/.prerender after bundling).
const DATA_DIR = path.join(process.cwd(), 'src', 'data');

export interface PartyInfo {
  name: string;
  color: string;
  bloc: string;
  seats_order: number;
}

export interface Meta {
  run_id: string | null;
  n_cases: number;
  parties: Record<string, PartyInfo>;
  hemicycle_order: string[];
  /** policy_area code -> localized filter/chip labels (from the utskott map) */
  policy_areas: Record<string, { sv: string; en: string }>;
  /** party -> programme versions, oldest-first, each visible from its adoption
   * date. Mirrors PARTY_PROGRAMS so a citation can be resolved to the version
   * in force on the vote date. Absent on exports predating the registry. */
  party_programs?: Record<string, { slug: string; from: string }[]>;
  attribution: string;
}

export interface ActualPosition {
  position: string;
  n_ja: number;
  n_nej: number;
  n_avstar: number;
  n_franvarande: number;
  cohesion: number;
  /** The party itself moved the reservation being voted down (procedural fact, no AI). */
  authored_reservation?: boolean;
}

export interface AiDecision {
  /** On p6 runs this is DERIVED from `hallning`, never predicted directly. */
  rost: string;
  /**
   * p6: the plan's stance on what the counter-proposal DEMANDS — the field the
   * agent actually decides. Null on the older p4/p5 runs, which supplied `rost`.
   */
  hallning?: 'stodjer' | 'avvisar' | null;
  /** p6: did the plan reach the committee's actual reason for its position? */
  plan_tacker_utskottets_skal?: 'ja' | 'nej' | null;
  /**
   * How far the plan reaches into what this vote turned on. Only 'explicit' can
   * carry a "the party voted against its own stated commitment" claim; 'off_axis'
   * means the committee's reason was procedural and the plan is silent on it.
   */
  tier?: 'explicit' | 'extrapolated' | 'off_axis' | null;
  confidence: string;
  coverage: string;
  motivering: string;
  citations: { document: string; quote: string; princip?: string; svag?: boolean }[];
  omvarld?: { paverkar: boolean; faktorer: { faktor: string; effekt: string }[] };
  flags: string[];
  model: string;
  /**
   * The party's own documents explicitly implied opposing the committee, yet it
   * voted Ja. 'strict' = the agent was also highly confident. Null otherwise.
   */
  program_override?: 'strict' | 'loose' | null;
  /** English translation; null until the translation batch has run. */
  en?: {
    motivering: string;
    citations: { quote: string; princip: string }[];
    omvarld: { faktor: string; effekt: string }[];
  } | null;
}

/**
 * The division re-run with documented commitments overriding the floor: every
 * party whose plan stated the commitment outright (tier `explicit`) and which
 * voted the other way is moved onto the plan's side, everyone else keeps their
 * real seat counts. `parties` is exactly the index row's `missx`. Absent when no
 * party qualifies; `outcome` is null on an exact tie (decided by lot in reality,
 * so never reported as a flip). See pipeline/aidag/aivotes.py.
 */
export interface Flip {
  parties: string[];
  actual: { ja: number; nej: number; outcome: string | null };
  counterfactual: { ja: number; nej: number; outcome: string | null };
  flips: boolean;
}

/** Per policy area x party: how often the real vote followed the party's plan.
 *
 * Denominators are votes where the party took a side (Ja/Nej) — the same gate
 * the published gap uses. `abstained` sits beside `n`, never inside it. */
export interface AreaCell {
  n: number;
  follows: number;
  follow_rate: number | null;
  abstained: number;
  explicit_n: number;
  explicit_gap: number;
  explicit_gap_rate: number | null;
}

export interface AreaStats {
  /** area codes, most cases first */
  areas: string[];
  per_area: Record<
    string,
    { n_cases: number; all_parties: AreaCell; per_party: Record<string, AreaCell> }
  >;
  per_party: Record<string, AreaCell>;
  overall: AreaCell;
}

export interface FlipSummary {
  n_cases: number;
  n_with_movers: number;
  n_flipped: number;
  /** flipped by a single party's documented commitments alone */
  n_solo: number;
  /** tied on one side of the comparison, so undecidable in either direction */
  n_indeterminate: number;
  direction: { ja_to_nej: number; nej_to_ja: number };
  per_party: Record<string, { movers: number; flips: number; solo: number }>;
  per_area: Record<
    string,
    { n_cases: number; with_movers: number; flipped: number; flip_rate: number | null }
  >;
  /** every flipped division, newest first — uncapped; callers slice for display */
  cases: {
    votering_id: string;
    datum: string;
    rubrik: string;
    utskott: string;
    policy_area: string | null;
    parties: string[];
    solo: boolean;
    outcome: string;
    counterfactual: string;
    margin: number;
  }[];
}

/** English case texts; null until the translation batch has run. */
export interface CaseEn {
  rubrik: string;
  dok_titel: string;
  forslag_text: string;
  notis: string;
  alternatives: string[]; // parallel to CaseData.alternatives
}

export interface CompactMeanings {
  ja_sv: string;
  nej_sv: string;
  avstar_sv: string;
  ja_en: string;
  nej_en: string;
  avstar_en: string;
}

/** Case metadata (deterministic facts + grounded synthesis); null until generated. */
export interface CaseMeta {
  type: string;
  /** stable policy-area code (language-independent filter key) */
  policy_area: string;
  subject: { sv: string; en: string };
  /** what is materially at stake / why it matters — NOT the literal Ja/Nej meanings */
  at_stake: { sv: string; en: string };
  subtopics: string[];
  parties_involved: string[];
}

export interface CaseData {
  compact?: CompactMeanings;
  meta?: CaseMeta;
  en?: CaseEn | null;
  votering_id: string;
  rm: string;
  beteckning: string;
  punkt: number;
  dok_id: string;
  datum: string;
  utskott: string;
  rubrik: string;
  dok_titel: string;
  /** committee's pre-decision summary (utsknotis) — the neutral "what this is about" lead */
  sammanfattning?: string;
  forslag_text: string;
  notis: string;
  alternatives: {
    alt_id: string;
    text: string;
    source_partier: string[];
    /** recovered, party-blind summary of what this reservation proposes; null until fetched */
    substance?: { sv: string; en: string };
  }[];
  actual: Record<string, ActualPosition>;
  ai: Record<string, AiDecision>;
  /** counterfactual outcome; absent when no party's plan explicitly diverged */
  flip?: Flip;
  seats: [string, string, string, string][]; // [parti, rost, namn, valkrets]
  references: { dok_id: string; typ: string; label: string; titel: string; undertitel: string }[];
  source_url: string;
  fulltext_url: string;
  votering_url: string;
  riksdagen_url: string;
}

export interface IndexRow {
  id: string;
  datum: string;
  rm: string;
  bet: string;
  punkt: number;
  utskott: string;
  rubrik: string;
  rubrik_en?: string | null;
  titel: string;
  agree: number;
  compared: number;
  hasAi: boolean;
  /** stable policy-area code for the browser filter (present once metadata generated) */
  policy_area?: string;
  /** case type: budget|proposition|motion|other */
  type?: string;
  /** precomputed lowercased search blob: rubrik + rubrik_en + titel + bet + subject sv/en + subtopics */
  search?: string;
  miss?: string[];
  /** subset of `miss` whose evidence tier is `explicit` */
  missx?: string[];
  /** 1 when moving every `missx` party onto its plan's side flips the chamber's
   * decision. Absent otherwise, to keep the client-fetched index lean. */
  flip?: 1;
}

function readJson<T>(rel: string): T {
  return JSON.parse(fs.readFileSync(path.join(DATA_DIR, rel), 'utf-8')) as T;
}

export const getMeta = (): Meta => readJson<Meta>('meta.json');
export const getIndex = (): IndexRow[] => readJson<IndexRow[]>('index/cases-index.json');
export const getCase = (id: string): CaseData => readJson<CaseData>(`cases/${id}.json`);

export function getAggregate<T>(name: string): T | null {
  const p = path.join(DATA_DIR, 'aggregates', `${name}.json`);
  return fs.existsSync(p) ? (JSON.parse(fs.readFileSync(p, 'utf-8')) as T) : null;
}

export function listCaseIds(): string[] {
  return fs
    .readdirSync(path.join(DATA_DIR, 'cases'))
    .filter((f) => f.endsWith('.json'))
    .map((f) => f.replace(/\.json$/, ''));
}

export function listCorpusDocs(): string[] {
  const dir = path.join(DATA_DIR, 'corpus');
  if (!fs.existsSync(dir)) return [];
  return fs
    .readdirSync(dir)
    .filter((f) => f.endsWith('.txt'))
    .map((f) => f.replace(/\.txt$/, ''));
}

/** The corpus grouped by the party whose filename encodes it.
 *
 * The position of the code is NOT fixed: programmes and budget motions are
 * `<kind>-<party>-<year>` (`partiprogram-kd-2025`) but the manifestos are
 * `<kind>-<year>-<party>` (`valmanifest-2022-kd`). Scanning every segment for a
 * known code covers both; keying on the second segment silently dropped all
 * eight manifestos into `shared` — and the manifestos are half of what the
 * agents actually read. Party codes never collide with the numeric segments, so
 * the scan is safe. Anything with no code (the Tidö agreement) lands in `shared`
 * rather than being dropped.
 *
 * Shared by /parti/ and /parti/[code], which must not disagree about which
 * documents are a party's own.
 */
export function corpusDocsByParty(codes: string[]): {
  byParty: Record<string, string[]>;
  shared: string[];
} {
  const byParty: Record<string, string[]> = Object.fromEntries(codes.map((c) => [c, []]));
  const shared: string[] = [];
  for (const slug of listCorpusDocs().sort()) {
    const code = slug.split('-').map((seg) => seg.toUpperCase()).find((seg) => seg in byParty);
    if (code) byParty[code].push(slug);
    else shared.push(slug);
  }
  return { byParty, shared };
}

export function getCorpusDoc(slug: string): string {
  return fs.readFileSync(path.join(DATA_DIR, 'corpus', `${slug}.txt`), 'utf-8');
}

/** The structured extraction for a document, or null when it has none.
 *
 * 23 of the 40 documents are re-extracted from their source PDFs into blocks
 * with roles and reading order (`aidag extract-corpus`); the 16 budgetmotioner
 * and Tidöavtalet are not, and null is how the document page knows to fall back
 * to `formatCorpusDoc()`. Absence is the normal case for those 17, not an
 * error — which is why this returns null rather than throwing.
 */
export function getCorpusBlocks(slug: string): CorpusBlockFile | null {
  const p = path.join(DATA_DIR, 'corpus', 'blocks', `${slug}.json`);
  if (!fs.existsSync(p)) return null;
  return JSON.parse(fs.readFileSync(p, 'utf-8')) as CorpusBlockFile;
}

/** How the whole corpus sets its words, for the title casing in doctext.ts.
 *
 * Corpus-wide rather than per document, and that is the point: the casing of a
 * title word is read off the prose that attests it, and one document is often
 * too small to attest its own. `valmanifest-2022-kd` is 104 blocks and uses
 * neither "vid", "bra" nor "bukt" outside its capitalised headings, so on its
 * own evidence those three stayed in capitals mid-sentence; across all 23 they
 * are lowercased 286, 150 and 1 times.
 *
 * Read once per build — 23 files, ~9,400 blocks — and memoised, because it is
 * the same answer for all 23 document pages.
 */
let lexicon: CasingLexicon | null = null;
export function getCorpusLexicon(): CasingLexicon {
  if (!lexicon) {
    const files = listCorpusDocs()
      .map(getCorpusBlocks)
      .filter((f): f is CorpusBlockFile => f !== null);
    lexicon = casingLexicon(files);
  }
  return lexicon;
}

/** The per-block citation aggregates for a document, or null when it has none.
 *
 * Written by `aidag build-anchors` and shipped by `export_site
 * .export_blocks_and_anchors()`. Absent for the 17 documents without blocks, and
 * absent for a re-extracted document no decision has cited — both are the normal
 * case, so this returns null rather than throwing. The heavier half (one row per
 * citing vote) is not read here at all: it sits under `public/data/anchors/` and
 * the browser fetches it when a panel is opened.
 */
export function getCorpusAnchors(slug: string): AnchorSummary | null {
  const p = path.join(DATA_DIR, 'corpus', 'anchors', `${slug}.json`);
  if (!fs.existsSync(p)) return null;
  return JSON.parse(fs.readFileSync(p, 'utf-8')) as AnchorSummary;
}

export interface DocCites {
  /** blocks of the document at least one citation landed on */
  lines: number;
  /** distinct divisions that cited it, however many of its lines each quoted */
  votes: number;
  kept: number;
  diverged: number;
}

/** How much of each document the votes actually leaned on, keyed by slug.
 *
 * Read off the committed citation index (`aidag build-anchors` ->
 * src/data/corpus/anchors/), which is 23 small files at build time — the
 * per-vote rows behind these totals are the 8.3 MB that stay out of every page
 * until a reader opens a panel.
 *
 * `lines` and `votes` are different questions and both are worth printing: how
 * much of the document is under citation at all, and how many divisions leaned
 * on it — the same distinction the document pages draw between a block's
 * `decisions.n` and its `refs`. Absent for the 17 documents the p6 run does not
 * show the agents, and absent is the honest answer there: no citation can point
 * at a document nobody was given.
 */
export function corpusCitationStats(): Map<string, DocCites> {
  const out = new Map<string, DocCites>();
  for (const slug of listCorpusDocs()) {
    const a = getCorpusAnchors(slug);
    if (!a) continue;
    out.set(slug, {
      lines: Object.keys(a.blocks).length,
      votes: a.totals.decisions.n,
      kept: a.totals.decisions.kept,
      diverged: a.totals.decisions.diverged,
    });
  }
  return out;
}

/** The divisions whose citations landed somewhere in the corpus.
 *
 * `public/data/anchors/cases.json` is keyed by exactly that set — it is written
 * from the anchors' own refs (`export_site._write_case_titles`), so counting its
 * keys is a measurement rather than a proxy. The alternative, summing the
 * per-document totals, counts a division once per document it cited: 32,796
 * against 2,539.
 *
 * Lives under public/ because the document pages fetch it in the browser; this
 * reads the same file off disk at build time. Null when it has not been exported,
 * which is how the front page knows to leave the claim unsaid rather than print
 * a zero.
 */
export function getCitingVotes(): number | null {
  const p = path.join(DATA_DIR, '..', '..', 'public', 'data', 'anchors', 'cases.json');
  if (!fs.existsSync(p)) return null;
  const payload = JSON.parse(fs.readFileSync(p, 'utf-8')) as { cases: Record<string, unknown> };
  return Object.keys(payload.cases).length;
}

/** Slug of the corpus document a citation points at, or null if not published.
 *
 * `valmanifest` and `tidoavtalet` have exactly one version each, so party alone
 * resolves them. `partiprogram` does not: most parties replaced theirs mid-term
 * (KD 2015→2025, L 2021→2023→2025, S/MP/SD/V likewise), and a citation records
 * only the document class. The version the agent read is the last one adopted on
 * or before the vote — the same date gate that built its context — so resolving
 * needs `voteDate`. Callers without one get null rather than a link to the wrong
 * edition, which is what a year-granular guess would produce for votes falling
 * between January and an autumn congress.
 */
export function citationDocSlug(
  party: string,
  document: string,
  voteDate?: string,
): string | null {
  if (document === 'valmanifest') return `valmanifest-2022-${party.toLowerCase()}`;
  if (document === 'tidoavtalet') return 'tidoavtalet-2022';
  if (document === 'partiprogram') {
    if (!voteDate) return null;
    const versions = getMeta().party_programs?.[party.toUpperCase()];
    if (!versions?.length) return null;
    // oldest-first, so the last one already adopted is the applicable edition
    let hit: string | null = null;
    for (const v of versions) {
      if (v.from <= voteDate) hit = v.slug;
      else break;
    }
    return hit;
  }
  return null;
}

/**
 * Readable ink for a letter drawn on top of a party's fill color.
 * Uses WCAG relative luminance so light brand colors (SD yellow, M sky-blue,
 * MP lime) get dark text and dark ones (KD navy, V crimson) get white.
 */
export function partyInk(hex: string): string {
  const h = hex.replace('#', '');
  const n = h.length === 3 ? h.split('').map((c) => c + c).join('') : h;
  const toLin = (v: number) => {
    const s = v / 255;
    return s <= 0.03928 ? s / 12.92 : ((s + 0.055) / 1.055) ** 2.4;
  };
  const r = toLin(parseInt(n.slice(0, 2), 16));
  const g = toLin(parseInt(n.slice(2, 4), 16));
  const b = toLin(parseInt(n.slice(4, 6), 16));
  const lum = 0.2126 * r + 0.7152 * g + 0.0722 * b;
  return lum > 0.42 ? '#1a1712' : '#ffffff';
}

/** URL text-fragment for deep-linking a verbatim quote inside a document page.
 *
 * Invisible characters go first: the browser matches against what is drawn, and
 * the document page strips them, so a quote carrying one (51 do — the BEL after
 * `valmanifest-2022-s`'s bullet glyph) would encode a character the page does
 * not contain and match nothing. */
export function quoteFragment(quote: string): string {
  const words = stripInvisible(quote).trim().split(/\s+/);
  if (words.length <= 8) return frag(words.join(' '));
  const start = words.slice(0, 5).join(' ');
  const end = words.slice(-4).join(' ');
  return `${frag(start)},${frag(end)}`;
}

/** `encodeURIComponent` plus the hyphen, which it leaves literal.
 *
 * The directive grammar is `[prefix-,]textStart[,textEnd][,-suffix]`, and the
 * parser splits on commas and applies that `-` test to the still-encoded token,
 * before percent-decoding. So a first term ending in a hyphen is consumed as a
 * *prefix* — which must immediately precede the match — and the quote then
 * matches nothing at all: no highlight, no scroll, no error, the reader lands at
 * the top of a 90-page programme. Swedish coordinated compounds put a trailing
 * hyphen on a word constantly ("mötes- och föreningsfriheten", "grundskole-
 * eller gymnasieutbildning") and the five-word head lands on one in 119 of
 * full-v4's 77,599 rendered links. `%2D` percent-decodes back to `-` after the
 * syntax check, so the text being searched for is unchanged.
 *
 * The blanket replace is safe: `encodeURIComponent` escapes to uppercase `%XX`,
 * so a `-` in its output can only have come from a literal one in the input. */
function frag(s: string): string {
  return encodeURIComponent(s).replace(/-/g, '%2D');
}
